repository: mo-shakiba/intCV
favicon: images/favicon.ico

version: 2

name: Mohammad Sadra Moazzen
title: Researcher
email: moazzensadra81@gmail.com

darkmode: never
last_update: Apr 11, 2024

github_username:  sadra1381am
linkedin_username: sadram

about_profile_image: images/profile.jpg 
about_content: |
  **CV: [PDF](https://sadra1381am.github.io/CV.pdf)**
  
  As an undergraduate in cellular and molecular biology, l excel in Python and data analysis, with a keen interest in neuroscience and memory research.
  
  I am most skilled in: <mark>Python</mark>, <mark>Data science</mark> and <mark>Neuroscience</mark>
  
content:
  - title: Education
    layout: list
    content:
      - layout: top-middle
        title: Ferdowsi University of Mashhad
        caption: 2021 - 2025
        sub_title: B.Sc. Cell and Molecular Biology

remote_theme: mo-shakiba/intCV

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
