# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Mohammad Sadra Moazzen
title: Researcher
email: moazzensadra81@gmail.com
# website: int-n.info
# Dark Mode (true/false/never)
darkmode: never

# Social links
# twitter_username: facespics
github_username:  sadra1381am
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: sadram
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000
# Additional icon links
additional_links:
- title: Email
  icon: fas fa-solid fa-envelope
  url: 'mailto:moazzensadra81@gmail.com'
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)


# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg 
about_content: | # this will include new lines to allow paragraphs
  **CV: [PDF](https://sadra1381am.github.io/CV.pdf)**
  
  As an undergraduate in cellular and molecular biology, l excel in Python and data analysis, with a keen interest in neuroscience and memory research.
  
  I am most skilled in: <mark>Python</mark>, <mark>Data science</mark> and <mark>Neuroscience</mark>
  
content:
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Ferdowsi University of Mashhad
        caption: 2021 - 2025
        sub_title: B.Sc. Cell and Molecular Biology
# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
